spring:
    output:
      ansi:
        enabled: ALWAYS
    profiles:
      active: default
    data:
      mongodb:
        uri: mongodb://127.0.0.1/tangerine
    kafka:
      bootstrap-servers: localhost:2181

endpoints:
  health:
    sensitive: "false"
management:
  security:
    enabled: "false"
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

security:
  user:
    name: dug
    password: dug
  basic:
    enabled: "false"
server:
  port: "8081"

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: dug

mq:
  servers[1]:
    queueManager: IIBDGVA85
    channel: CLOUD.ADMIN.SVRCONN
    connName: iibdgva85-6382.qm.us-south.mq.appdomain.cloud(32279)
    user: nbavu
    password: AcJQQR_ozaNSSvf4mOcNpbHOF99xHVJrqGpeF0Skfjg8
  servers[0]:
    queueManager: QM1
    channel: CLOUD.ADMIN.SVRCONN
    connName: qm1-252a.qm.us-south.mq.appdomain.cloud(32306)
    user: shimona1
    password: NED4X46sMkf749mRYAZiUhkDfoy5lvUFA8RT0i19WTt0

#  spring.data.mongodb.database=wingtiptoysmongodb
#  spring.data.mongodb.uri=mongodb://wingtiptoysmongodb:AbCdEfGhIjKlMnOpQrStUvWxYz==@wingtiptoysmongodb.documents.azure.com:10255/?ssl=true&replicaSet=globaldb

#spring:
#  data:
#    mongodb:
#      database: mongodb-osimosimdev
#      uri: mongodb://mongodb-osimosimdev:dYVNK1YaknijEKg1N2pNctOT6QkZXBMQXBynUrMgDHcewUXQe90FmJ2TIl65DuHuG5jETLgNxudpfNJhnToTYg==@mongodb-osimosimdev.documents.azure.com:10255/?ssl=true&replicaSet=globaldb

ims:
  kafkaBootstrapServers: localhost:9092
  kafkaRetries: "1"
  kafka:
    supplyTopic: "SUPPLY_TOPIC"
    retailTopic: "RETAIL_TOPIC"
    catalogTopic: "CATALOG_TOPIC"
catalog:
  spark:
    master: local
    appname: Catalog_Data_Processor
    file:
      path: Product.txt
  #catalog.spark.mongo.db.url=mongodb://safeway@localhost:27017/?ssl=true&replicaSet=globaldb
    mongo:
      db:
        url: mongodb://127.0.0.1:27017
    sql:
      mongo:
        user: test1
        password: test1
        database: tangerine1
        collection: Item1
    maxItems: 20
  rogCodes: SNCA,SNHA,AIMT

  metadata:
    broker:
      list: localhost:9092